import 'order.dart';
import 'driver.dart';
import 'user.dart';

class DriverReview {
  final int id;
  final int orderId;
  final int driverId;
  final int customerId;
  final int rating; // 1-5
  final String? comment;
  final bool isAutoGenerated;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  // Relationship data
  final Order? order;
  final Driver? driver;
  final User? customer;

  DriverReview({
    required this.id,
    required this.orderId,
    required this.driverId,
    required this.customerId,
    required this.rating,
    this.comment,
    this.isAutoGenerated = false,
    this.createdAt,
    this.updatedAt,
    this.order,
    this.driver,
    this.customer,
  });

  factory DriverReview.fromJson(Map<String, dynamic> json) {
    return DriverReview(
      id: json['id'] ?? 0,
      orderId: json['order_id'] ?? 0,
      driverId: json['driver_id'] ?? 0,
      customerId: json['customer_id'] ?? 0,
      rating: json['rating'] ?? 1,
      comment: json['comment'],
      isAutoGenerated: json['is_auto_generated'] ?? false,
      createdAt: json['created_at'] != null ? DateTime.parse(json['created_at']) : null,
      updatedAt: json['updated_at'] != null ? DateTime.parse(json['updated_at']) : null,
      order: json['order'] != null ? Order.fromJson(json['order']) : null,
      driver: json['driver'] != null ? Driver.fromJson(json['driver']) : null,
      customer: json['customer'] != null ? User.fromJson(json['customer']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'order_id': orderId,
      'driver_id': driverId,
      'customer_id': customerId,
      'rating': rating,
      if (comment != null) 'comment': comment,
      'is_auto_generated': isAutoGenerated,
      if (createdAt != null) 'created_at': createdAt!.toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt!.toIso8601String(),
      if (order != null) 'order': order!.toJson(),
      if (driver != null) 'driver': driver!.toJson(),
      if (customer != null) 'customer': customer!.toJson(),
    };
  }

  DriverReview copyWith({
    int? id,
    int? orderId,
    int? driverId,
    int? customerId,
    int? rating,
    String? comment,
    bool? isAutoGenerated,
    DateTime? createdAt,
    DateTime? updatedAt,
    Order? order,
    Driver? driver,
    User? customer,
  }) {
    return DriverReview(
      id: id ?? this.id,
      orderId: orderId ?? this.orderId,
      driverId: driverId ?? this.driverId,
      customerId: customerId ?? this.customerId,
      rating: rating ?? this.rating,
      comment: comment ?? this.comment,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      order: order ?? this.order,
      driver: driver ?? this.driver,
      customer: customer ?? this.customer,
    );
  }
}