// lib/models/entities/driver_review.dart
import 'package:del_pick/Models/Entities/user.dart';

import 'driver.dart';
import 'order.dart';

class DriverReview {
  final int id;
  final int orderId;
  final int driverId;
  final int customerId;
  final int rating;
  final String? comment;
  final bool isAutoGenerated;
  final DateTime createdAt;
  final DateTime updatedAt;

  // Relations
  final Driver? driver;
  final User? customer;
  final Order? order;

  DriverReview({
    required this.id,
    required this.orderId,
    required this.driverId,
    required this.customerId,
    required this.rating,
    this.comment,
    required this.isAutoGenerated,
    required this.createdAt,
    required this.updatedAt,
    this.driver,
    this.customer,
    this.order,
  });

  factory DriverReview.fromJson(Map<String, dynamic> json) {
    return DriverReview(
      id: json['id'] as int,
      orderId: json['order_id'] as int,
      driverId: json['driver_id'] as int,
      customerId: json['customer_id'] as int,
      rating: json['rating'] as int,
      comment: json['comment'] as String?,
      isAutoGenerated: json['is_auto_generated'] as bool,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      driver: json['driver'] != null ? Driver.fromJson(json['driver']) : null,
      customer: json['customer'] != null ? User.fromJson(json['customer']) : null,
      order: json['order'] != null ? Order.fromJson(json['order']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'order_id': orderId,
      'driver_id': driverId,
      'customer_id': customerId,
      'rating': rating,
      'comment': comment,
      'is_auto_generated': isAutoGenerated,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      if (driver != null) 'driver': driver!.toJson(),
      if (customer != null) 'customer': customer!.toJson(),
      if (order != null) 'order': order!.toJson(),
    };
  }
}